import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ScrollSmootherWrapper from "@/components/ScrollSmootherWrapper";

export const metadata: Metadata = {
  title: "HAGE | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased"> 
        <Header />
        <ScrollSmootherWrapper>  
          {children}
          <SpeedInsights />
          <Footer />
        </ScrollSmootherWrapper>
      </body>
    </html>
  );
}
