import type { Metadata } from "next";
import "./globals.css";
import Header from "./global_components/Header";

export const metadata: Metadata = {
  title: "HAGE | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        {children}
      </body>
    </html>
  );
}
